feat: add pagination to deployments [6]
liftedinit/ghostcloud-cosmos-frontend pull request #33
Opened 2023-12-21 19:44 UTC by nblenke

## Description

- Adding pagination to deployments page
- bump @liftedinit/gcjs to 0.0.6

## Related Issue

Fixes #6

## Testing

## Breaking Changes (if applicable)

## Screenshots (if applicable)

https://github.com/liftedinit/ghostcloud-cosmos-frontend/assets/649166/1d074c21-caf9-4aa7-ad26-4043f3b15759

## Checklist:

- [x] I have read and followed the CONTRIBUTING guidelines for this project.
- x] I have added or updated tests and they pass.
- [x] I have added or updated documentation and it is accurate.
- [x] I have noted any breaking changes in this module or downstream modules.

2024-01-03 15:38 UTC, fmorency requested changes
Thanks for the PR!

It doesn't work past page 2. Can you fix and add a test for it?

2024-01-03 15:38 UTC, fmorency commented on lib/ghostcloud.ts
> +export const useFetchMetas = (): [
Did you try using `react-query` [paginated queries](https://tanstack.com/query/v4/docs/react/guides/paginated-queries) instead of doing it "by hand"?

2024-01-03 15:49 UTC, fmorency commented
FYI, the pagination goes past page 2 after refreshing the page.

2024-01-06 23:21 UTC, nblenke commented on lib/ghostcloud.ts
> +export const useFetchMetas = (): [
I've refactored to use the [offset example](https://tanstack.com/query/v4/docs/react/guides/paginated-queries) which leverages `keepPreviousData`.

2024-01-06 23:25 UTC, nblenke commented
> FYI, the pagination goes past page 2 after refreshing the page.

I noticed this as well after more testing, I think this was a combination of not refetching when adding deployments and my implementation of using pagination key being a bit flaky

2024-01-08 15:48 UTC, merged